spring:
  application:
    name: oj
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/oj
    username: oj
    password: password
    type: com.alibaba.druid.pool.DruidDataSource